export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const ADD_SHAPE = 'ADD_SHAPE';
export const UPDATE_SHAPE = 'UPDATE_SHAPE';
export const DELETE_SHAPE = 'DELETE_SHAPE';
export const DELETE_SHAPES = 'DELETE_SHAPES';
export const UPDATE_SHAPE_ATTRIBUTE = 'UPDATE_SHAPE_ATTRIBUTE';

export const ADD_GROUP = 'ADD_GROUP';
export const DELETE_GROUP = 'DELETE_GROUP';
export const BRING_ONE_LEVEL = 'BRING_ONE_LEVEL';
export const SEND_ONE_LEVEL = 'SEND_ONE_LEVEL';
export const BRING_TO_TOP = 'BRING_TO_TOP';
export const SEND_TO_BACK = 'SEND_TO_BACK';
export const SELECT_ELEMENT = 'SELECT_ELEMENT';
export const ADD_SHAPE_TO_GROUP = 'ADD_SHAPE_TO_GROUP';
export const DELETE_SHAPE_FROM_GROUP = 'DELETE_SHAPE_FROM_GROUP';
export const MOVE_SHAPE_TO_OTHER_GROUP = 'MOVE_SHAPE_TO_OTHER_GROUP';